FROM golang:1.14 AS builder
WORKDIR /go/src/github.com/polyse/database

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN GOOS=linux CGO_ENABLED=0 go test -v ./...
